name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - 'web/**'
      - 'packages/**'
      - '.gitea/workflows/**'
  workflow_dispatch:

env:
  REGISTRY: registry.jiun.dev

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/selectchatgpt-server:${{ gitea.sha }}
            ${{ env.REGISTRY }}/selectchatgpt-server:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-server:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-server:buildcache,mode=max

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/selectchatgpt-web:${{ gitea.sha }}
            ${{ env.REGISTRY }}/selectchatgpt-web:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-web:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-web:buildcache,mode=max

  update-manifests:
    needs: [build-server, build-web]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update image tags in kustomization
        run: |
          cd k8s
          sed -i "s/newTag: .*/newTag: ${{ gitea.sha }}/" kustomization.yaml
          cat kustomization.yaml

      - name: Commit and push
        run: |
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.jiun.dev"
          git add k8s/kustomization.yaml
          git diff --staged --quiet || git commit -m "chore: update image tags to ${{ gitea.sha }}"
          git push
