name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'web/**'
      - 'packages/**'
      - '.gitea/workflows/**'
  workflow_dispatch:

env:
  REGISTRY: registry.jiun.dev
  IAC_REPO: jiunbae/IaC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/selectchatgpt-server:${{ gitea.sha }}
            ${{ env.REGISTRY }}/selectchatgpt-server:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-server:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-server:buildcache,mode=max

      - name: Build and push web (dev)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/selectchatgpt-web:dev-${{ gitea.sha }}
            ${{ env.REGISTRY }}/selectchatgpt-web:dev-latest
          build-args: |
            NEXT_PUBLIC_API_URL=https://selectchatgpt.internal.jiun.dev
            NEXT_PUBLIC_GA_ID=
            NEXT_PUBLIC_ADSENSE_ID=
          cache-from: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-web:dev-buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-web:dev-buildcache,mode=max

      - name: Build and push web (prod)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/selectchatgpt-web:${{ gitea.sha }}
            ${{ env.REGISTRY }}/selectchatgpt-web:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}
            NEXT_PUBLIC_ADSENSE_ID=${{ secrets.NEXT_PUBLIC_ADSENSE_ID }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-web:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/selectchatgpt-web:buildcache,mode=max

      - name: Update IaC repo
        run: |
          git clone https://x-access-token:${{ secrets.IAC_GITHUB_TOKEN }}@github.com/${{ env.IAC_REPO }}.git iac

          # Update dev overlay
          cd iac/kubernetes/overlays/dev/selectchatgpt
          sed -i '/selectchatgpt-server/!b;n;s/newTag: .*/newTag: ${{ gitea.sha }}/' kustomization.yaml
          sed -i '/selectchatgpt-web/!b;n;s/newTag: .*/newTag: dev-${{ gitea.sha }}/' kustomization.yaml
          cat kustomization.yaml

          # Update prod overlay
          cd ../../../overlays/prod/selectchatgpt
          sed -i 's/newTag: .*/newTag: ${{ gitea.sha }}/' kustomization.yaml
          cat kustomization.yaml

          cd ../../../../
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.jiun.dev"
          git add kubernetes/overlays/dev/selectchatgpt/kustomization.yaml
          git add kubernetes/overlays/prod/selectchatgpt/kustomization.yaml
          git diff --staged --quiet || git commit -m "chore(selectchatgpt): update image tags to ${{ gitea.sha }}"
          git push
