import TurndownService from "turndown"
import type { ChatMessage } from "~src/types"

const turndownService = new TurndownService({
  headingStyle: 'atx',
  codeBlockStyle: 'fenced',
  bulletListMarker: '-',
  emDelimiter: '*'
})

turndownService.addRule('codeBlocks', {
  filter: (node) => {
    return node.nodeName === 'PRE' && node.querySelector('code') !== null
  },
  replacement: (content, node) => {
    const codeElement = (node as HTMLElement).querySelector('code')
    const language = codeElement?.className?.match(/language-(\w+)/)?.[1] || ''
    const code = codeElement?.textContent || content
    return `\n\`\`\`${language}\n${code.trim()}\n\`\`\`\n`
  }
})

turndownService.addRule('inlineCode', {
  filter: (node) => {
    return node.nodeName === 'CODE' && node.parentNode?.nodeName !== 'PRE'
  },
  replacement: (content) => {
    return `\`${content}\``
  }
})

export function htmlToMarkdown(html: string): string {
  return turndownService.turndown(html)
}

export function convertToMarkdown(messages: ChatMessage[], title: string): string {
  const lines: string[] = []

  lines.push(`# ${title}`)
  lines.push('')
  lines.push(`> Source: ${window.location.href}`)
  lines.push(`> Generated by SelectChatGPT`)
  lines.push('')
  lines.push('---')
  lines.push('')

  messages.forEach((message, index) => {
    const roleLabel = message.role === 'user' ? '**User**' : '**ChatGPT**'
    lines.push(`## ${roleLabel}`)
    lines.push('')

    const markdown = htmlToMarkdown(message.html)
    lines.push(markdown)
    lines.push('')

    if (index < messages.length - 1) {
      lines.push('---')
      lines.push('')
    }
  })

  return lines.join('\n')
}
