import type { ExportMessage, ExportStyle, ExportStyleType } from './types';
import { getExportStyle } from './styles';

function applyStyles(element: HTMLElement, styles: Partial<CSSStyleDeclaration>): void {
  Object.assign(element.style, styles);
}

// Remove interactive elements that should not be in the exported output.
// This is not a security sanitizer.
function sanitizeHTML(html: string): string {
  const temp = document.createElement('div');
  temp.innerHTML = html;
  temp.querySelectorAll('button, [role="button"], .copy-button, svg.icon')
    .forEach(el => el.remove());
  return temp.innerHTML;
}

function processCodeBlocks(container: HTMLElement, style: ExportStyle): void {
  // Style pre > code blocks
  container.querySelectorAll('pre').forEach(pre => {
    applyStyles(pre as HTMLElement, style.codeBlock);
    const code = pre.querySelector('code');
    if (code) {
      code.style.backgroundColor = 'transparent';
      code.style.padding = '0';
    }
  });

  // Style inline code (not inside pre)
  if (style.inlineCode) {
    container.querySelectorAll('code').forEach(code => {
      if (code.parentElement?.tagName !== 'PRE') {
        applyStyles(code as HTMLElement, style.inlineCode!);
      }
    });
  }
}

export function createMessageElement(
  message: ExportMessage,
  style: ExportStyle
): HTMLDivElement {
  const wrapper = document.createElement('div');
  applyStyles(wrapper, style.messageWrapper);

  // Apply role-specific styles
  const roleStyle = message.role === 'user' ? style.userMessage : style.assistantMessage;
  applyStyles(wrapper, roleStyle);

  // Role label
  const roleLabel = document.createElement('div');
  roleLabel.textContent = message.role === 'user' ? 'You' : 'ChatGPT';
  applyStyles(roleLabel, style.roleLabel);
  wrapper.appendChild(roleLabel);

  // Content
  const content = document.createElement('div');
  content.innerHTML = sanitizeHTML(message.html);
  applyStyles(content, style.content);

  // Process code blocks inside content
  processCodeBlocks(content, style);

  // Style other elements
  content.querySelectorAll('p').forEach(p => {
    (p as HTMLElement).style.margin = '0 0 16px 0';
  });
  content.querySelectorAll('ul, ol').forEach(list => {
    (list as HTMLElement).style.margin = '0 0 16px 0';
    (list as HTMLElement).style.paddingLeft = '24px';
  });
  content.querySelectorAll('li').forEach(li => {
    (li as HTMLElement).style.marginBottom = '8px';
  });
  content.querySelectorAll('a').forEach(a => {
    (a as HTMLElement).style.color = '#10a37f';
    (a as HTMLElement).style.textDecoration = 'underline';
  });
  content.querySelectorAll('strong, b').forEach(el => {
    (el as HTMLElement).style.fontWeight = '600';
  });
  content.querySelectorAll('blockquote').forEach(bq => {
    (bq as HTMLElement).style.borderLeft = '3px solid #10a37f';
    (bq as HTMLElement).style.paddingLeft = '16px';
    (bq as HTMLElement).style.margin = '16px 0';
    (bq as HTMLElement).style.fontStyle = 'italic';
    (bq as HTMLElement).style.color = '#6b7280';
  });

  wrapper.appendChild(content);

  return wrapper;
}

export function createExportableElement(
  messages: ExportMessage[],
  title: string,
  styleType: ExportStyleType
): HTMLDivElement {
  const style = getExportStyle(styleType);

  const container = document.createElement('div');
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.top = '0';
  applyStyles(container, style.container);

  // Title
  if (title) {
    const titleEl = document.createElement('h1');
    titleEl.textContent = title;
    applyStyles(titleEl, style.header);
    container.appendChild(titleEl);

    // Subtitle with source info
    const subtitle = document.createElement('div');
    subtitle.textContent = 'Generated by SelectChatGPT';
    subtitle.style.fontSize = '12px';
    subtitle.style.color = styleType === 'chatgpt' ? '#8e8ea0' : '#9ca3af';
    subtitle.style.marginBottom = '24px';
    container.appendChild(subtitle);
  }

  // Messages
  messages.forEach((message, index) => {
    const msgEl = createMessageElement(message, style);
    if (index === messages.length - 1) {
      msgEl.style.borderBottom = 'none';
    }
    container.appendChild(msgEl);
  });

  return container;
}
