export type ExportStyleType = 'chatgpt' | 'clean';

export interface ExportProgress {
  stage: 'preparing' | 'rendering' | 'generating' | 'downloading';
  progress: number;
}

export interface ExportMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  html: string;
}

export interface ExportStyle {
  container: Partial<CSSStyleDeclaration>;
  header: Partial<CSSStyleDeclaration>;
  messageWrapper: Partial<CSSStyleDeclaration>;
  userMessage: Partial<CSSStyleDeclaration>;
  assistantMessage: Partial<CSSStyleDeclaration>;
  roleLabel: Partial<CSSStyleDeclaration>;
  content: Partial<CSSStyleDeclaration>;
  codeBlock: Partial<CSSStyleDeclaration>;
  inlineCode?: Partial<CSSStyleDeclaration>;
}

export class ExportError extends Error {
  constructor(
    message: string,
    public readonly code: 'RENDER_FAILED' | 'DOWNLOAD_FAILED' | 'MEMORY_ERROR'
  ) {
    super(message);
    this.name = 'ExportError';
  }
}

// Export styling options
export type LetterSpacing = 'tighter' | 'tight' | 'normal' | 'wide' | 'wider';
export type LineHeight = 'tight' | 'snug' | 'normal' | 'relaxed' | 'loose';
export type FontSize = 'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl';
export type FontFamily = 'system' | 'pretendard' | 'noto-sans-kr' | 'noto-serif-kr' | 'ibm-plex-sans-kr';
export type MessageGap = 'none' | 'sm' | 'md' | 'lg' | 'xl';
export type ContentPadding = 'none' | 'sm' | 'md' | 'lg' | 'xl';
export type PageSize = 'a4' | 'letter' | 'a5';

// Margin preset options
export type MarginPreset =
  | 'none'        // 0mm - no margin
  | 'minimal'     // 5mm - minimal margin
  | 'compact'     // 10mm - compact (legacy)
  | 'normal'      // 15mm - normal (legacy)
  | 'wide'        // 25mm - wide (legacy)
  | 'a4-standard' // A4 standard: 20mm top/bottom, 25mm left/right
  | 'custom';     // User-defined

// Custom margin values (used when MarginPreset is 'custom')
export interface CustomMargin {
  top: string;    // e.g., '20mm'
  bottom: string;
  left: string;
  right: string;
}

// Legacy type alias for backward compatibility
export type Margin = MarginPreset;

// PDF header/footer options
export interface PdfHeaderFooterOptions {
  showBranding?: boolean;        // "Generated by SelectChatGPT" (default: false)
  showDate?: boolean;            // Top-left date (default: false)
  showTitle?: boolean;           // Top-center title (default: false)
  showPageNumbers?: boolean;     // Bottom-right page numbers (default: true)
  showDomain?: boolean;          // Bottom-left domain (default: false)
  customDomain?: string;         // Custom domain text (default: window.location.hostname)
}

export interface ExportOptions {
  // Text styling (image/pdf only)
  letterSpacing?: LetterSpacing;
  lineHeight?: LineHeight;
  fontSize?: FontSize;
  fontFamily?: FontFamily;

  // Spacing
  messageGap?: MessageGap;
  contentPadding?: ContentPadding;

  // Content filtering (markdown/image/pdf)
  hideUserMessages?: boolean;
  hideCodeBlocks?: boolean;

  // Layout (pdf only)
  pageSize?: PageSize;
  margin?: MarginPreset;
  customMargin?: CustomMargin;

  // PDF header/footer (pdf only)
  pdfHeaderFooter?: PdfHeaderFooterOptions;
}
